spring:
  application:
    name: tool-admin-main
  profiles:
    active: corp
  # JSON格式化配置
  jackson:
    # 日期格式化格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区
    time-zone: Asia/Shanghai
    # 序列化配置
    serialization:
      write-dates-as-timestamps: false
sa-token:
  token-style: tik
jasypt:
  encryptor:
    # 3.0更换了安全协议,不配置下面选项会报错 https://blog.51cto.com/no8g/6344380
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator